name: Lint and Unit tests

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  unit_tests:
    runs-on: self-hosted
    environment:
      name: 'Local'

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Prepare deployment
        run: |
          npm install

      - name: Lint
        run: |
          npm run lint

      - name: Unit tests
        run: |
          npm run test

      - name: Launch application locally
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_APPLICATION_TEST_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_APPLICATION_TEST_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_APPLICATION_TEST_TENANT_ID }}
          CosmosEndpoint:   ${{ vars.STAGE_COSMOS_ENDPOINT }}
          CosmosDatabaseId: ${{ vars.STAGE_COSMOS_DATABASE_ID }}
        run: |
          npm run dev > output/app_stdout.txt 2>&1 &
          sleep 20

      # Upload screenshots as artifacts
      - name: Upload outputs
        if: always()      
        uses: actions/upload-artifact@v4
        with:
          name: test-output
          path: output/

      - name: Stop the app
        if: always()      
        run: |
          npm stop || true
