name: Dev push triggers

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  owasp_dependencycheck:
    uses: ./.github/workflows/reuse/owasp_dependencycheck.yml
  unit_tests:
    uses: ./.github/workflows/reuse/unit_tests_lint.yml
    secrets: inherit    
  sonarqube:
    uses: ./.github/workflows/reuse/sonarqube.yml
    secrets: inherit    
