name: OWASP DependencyCheck

on:
  workflow_dispatch:

jobs:
  selenium_testing:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v4

      - name: Run OWASP DependencyCheck
        run: |
          /opt/dependency-check/bin/dependency-check.sh \
            --noupdate \
            --scan . \
            --out output/ \
            --format "ALL"

      # Upload screenshots as artifacts
      - name: Upload reports
        if: always()      
        uses: actions/upload-artifact@v4
        with:
          name: owasp-dependencycheck-reports
          path: output/
