name: Selenium tests

on:
  push:
    branches:
      - dev
      - main
  workflow_dispatch:

jobs:
  selenium_testing:
    runs-on: ubuntu-latest
    environment:
      name: 'Local'

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: >-
          --health-cmd="curl -s http://localhost:4444/wd/hub/status | grep 'ready'"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
          --shm-size=1gb
        ports:
          - 4444:4444

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Prepare deployment
        run: |
          mkdir deploy
          mkdir output

          # Copy package files for npm dependencies
          cp package*.json deploy/
          # Copy source code
          cp -r src/* deploy/
          # Install production dependencies in deploy folder
          cd deploy && npm install

      - name: Launch application locally
        env:
          AZURE_CLIENT_ID: ${{ secrets.AZURE_APPLICATION_TEST_CLIENT_ID }}
          AZURE_CLIENT_SECRET: ${{ secrets.AZURE_APPLICATION_TEST_CLIENT_SECRET }}
          AZURE_TENANT_ID: ${{ secrets.AZURE_APPLICATION_TEST_TENANT_ID }}
          CosmosEndpoint:   ${{ vars.STAGE_COSMOS_ENDPOINT }}
          CosmosDatabaseId: ${{ vars.STAGE_COSMOS_DATABASE_ID }}
        run: |
          npm run dev > output/app_stdout.txt 2>&1 &
          sleep 20

      - name: Run selenium tests
        env:
          SELENIUM_REMOTE_URL: http://localhost:4444/wd/hub      
        run: |
          npm run selenium 2>&1 | tee output/selenium_tests_stdout.txt
          # Check the exit status of the previous command
          if [ ${PIPESTATUS[0]} -ne 0 ]; then
            echo "Selenium tests failed!"
            exit 1  # Exit with a non-zero status to fail the job
          fi

      # Upload screenshots as artifacts
      - name: Upload screenshots
        if: always()      
        uses: actions/upload-artifact@v4
        with:
          name: selenium-output
          path: output/

      - name: Stop the app
        if: always()      
        run: |
          npm stop || true
