name: Nightly Update Package Lock

on:
  schedule:
    - cron: "0 0 * * *" # Runs nightly at midnight UTC
  workflow_dispatch:

defaults:
  run:
    working-directory: ./

jobs:
  update-package-lock:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: dev # Start from dev branch

    # Create/update update_dependencies branch
    - name: Create/Update branch
      run: |
        git checkout -b update_dependencies
        git push -f origin update_dependencies

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Delete package-lock.json
      run: rm -f package-lock.json

    - name: Generate new package-lock.json
      run: npm install --package-lock-only

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add -f package-lock.json
        git commit -m "Update package-lock.json [Nightly Update]"

    - name: Push changes
      run: |
        git push origin update_dependencies

  test_pipeline:
    needs: update-package-lock
    uses: ./.github/workflows/test_pipeline.yml
    secrets: inherit    
    with:
      branch: update_dependencies

  merge_if_successful:
    needs: test_pipeline
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Merge to dev and cleanup
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          
          # Checkout dev and merge update_dependencies
          git checkout dev
          git pull origin dev
          git merge origin/update_dependencies --ff-only -m "Update dependencies"
          git push origin dev
          
          # Delete the update_dependencies branch
          git push origin --delete update_dependencies